---
- name: Set Facts
  ansible.builtin.set_fact:
    dovecot_ldap_host: "{{ ldap_host | default('ldap' ~ ansible_domain ) }}"
    dovecot_ldap_bind_dn: "{{ ldap_bind_dn | default('') }}"
    dovecot_ldap_bind_pw: "{{ ldap_bind_pw | default('') }}"
    dovecot_ldap_base: "{{ ldap_search_base | default('dc=' ~ ( ansible_domain | split('.') | join('dc='))) }}"
  no_log: true

- name: Show LDAP configuration
  ansible.builtin.debug:
    msg:
    - "LDAP host : {{ dovecot_ldap_host }}"
    - "LDAP dn : {{ dovecot_ldap_bind_dn }}"
    - "LDAP base : {{ dovecot_ldap_base }}"

- name: Configure LDAP virtual account
  become: true
  ansible.builtin.template:
    src: templates/etc/dovecot/ldap.conf.j2
    dest: /etc/dovecot/ldap.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart dovecot
