---
- name: Load variables by operating system
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Install packages by operating system
  ansible.builtin.include_tasks: "install_{{ ansible_os_family | lower }}.yml"

- name: Configure FIREWALLD if enable_base_firewalld is defined
  when: enable_base_firewalld
  ansible.builtin.include_tasks: firewalld.yml

- name: Configure CRON if enable_service_openldap_cron is defined
  ansible.builtin.import_tasks: cron.yml
  when: enable_service_openldap_cron

- name: Configure TLS if slapd_ssl_internal is defined
  ansible.builtin.import_tasks: config_tls.yml
  when: slapd_ssl_internal
