---
- name: Load variables by operating system
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Install packages by operating system
  ansible.builtin.include_tasks: "install_{{ ansible_os_family | lower }}.yml"

- name: Configure FIREWALLD if enable_base_firewalld is defined
  when: enable_base_firewalld
  ansible.builtin.include_tasks: firewalld.yml
