---
- name: Configure DOVECOT if enable_service_dovecot is defined
  when:
    - enable_service_dovecot | bool
    - ansible_action in ['converge', 'cleanup']
  block:
    - name: Facts
      ansible.builtin.include_tasks: "facts.yml"

    - name: Include tasks
      ansible.builtin.include_tasks: "{{ ansible_action }}.yml"
      when: ansible_facts.os_family | lower in dovecot_supported_os
