---
- name: Configure CODEREADY repository
  become: true
  community.general.rhsm_repository:
    name:
      - "codeready-builder-for-rhel-{{ ansible_facts.distribution_major_version }}-x86_64-rpms"
  when:
    - ansible_facts.distribution == 'RedHat'
