---
- name: Configure CODEREADY repository if enable_repositories_codeready is enable
  when:
    - enable_repositories_codeready | bool
    - ansible_action in ['converge', 'cleanup']
  block:
    - name: Facts
      ansible.builtin.include_tasks: "facts.yml"

    - name: Include tasks
      ansible.builtin.include_tasks: "{{ ansible_action }}_{{ ansible_facts.os_family | lower }}.yml"
      when: ansible_facts.os_family | lower in codeready_supported_os
