---
- name: Configure APACHE if enable_service_apache is defined
  when:
    - enable_service_apache | bool
    - ansible_action in ['converge', 'cleanup']
  block:
    - name: Facts
      ansible.builtin.include_tasks: "facts.yml"

    - name: Include tasks
      ansible.builtin.include_tasks: "{{ ansible_action }}.yml"
      when: ansible_facts.os_family | lower in apache_supported_os
