---
galaxy_info:
  author: Yannick Sebastia
  description: Configure CodeReady repository
  license: GPL-3.0-only
  min_ansible_version: '2.1'
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags: []
dependencies: []
