---
- name: Configure GitLab runner when enable_gitlab_runner if defined
  when:
    - enable_gitlab_runner | bool
    - ansible_action in ['converge']
  block:
    - name: Facts
      ansible.builtin.include_tasks: "facts.yml"

    - name: Include tasks
      ansible.builtin.include_tasks: "{{ ansible_action }}.yml"
      when: ansible_facts.os_family | lower in gitlab_supported_os
