---
- name: Ensure qemu-guest-agent is installed
  ansible.builtin.include_tasks: "install_{{ ansible_os_family | lower }}.yml"
- name: Ensure qemu-guest-agent is running (and enabled at boot)
  become: true
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true
