---
- name: Converge
  hosts: all
  tasks:
    - name: "Include dovecot"
      ansible.builtin.include_role:
        name: "dovecot"
      vars:
        enable_service_dovecot: true
        enable_service_dovecot_auth_for_postfix: true
        enable_service_dovecot_ldap: true
        enable_service_dovecot_syslog: true
        dovecot_dependencies: true
