---
galaxy_info:
  author: Yannick Sebastia
  description: Configure OpenSSH
  license: GPL-3.0-only
  min_ansible_version: '2.1'
  namespace: sebastia
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
dependencies: []
