---
enable_service_postfix: false
enable_service_postfix_ldap: false
enable_service_postfix_dovecot_transport: true
enable_service_postfix_ldap_account: true
postfix_virtual_mailbox_base: /var/vmail
postfix_virtual_gid: vmail
postfix_virtual_uid: vmail
postfix_virtual_transport: dovecot
postfix_conf_ldap_account: /etc/postfix/LdapAccounts
postfix_conf_main:
  - name: relayhost
    value:
  - name: myhostname
    value: '{{ ansible_fqdn }}'
  - name: append_dot_mydomain
    value: 'no'
  - name: biff
    value: 'no'
  - name: mailbox_size_limit
    value: 0
  - name: myorigin
    value: '{{ ansible_fqdn }}'
  - name: inet_interfaces
    value: all
postfix_conf_mainvirtual:
  - name: virtual_alias_domains
    value:
  - name: virtual_alias_expansion_limit
    value: 3000
  - name: virtual_gid_maps
    value: 'static:{{ postfix_virtual_gid }}'
  - name: virtual_mailbox_base
    value: '{{ postfix_virtual_mailbox_base }}'
  - name: virtual_mailbox_domains
    value: '{{ ansible_domain }}'
  - name: virtual_uid_maps
    value: 'static:{{ postfix_virtual_uid }}'
