---
- name: Converge
  hosts: all
  tasks:
    - name: "Bootstrap DOCKER service"
      ansible.builtin.include_role:
        name: "bootstrap"
      vars:
        enable_docker_service: true
        enable_repositories_docker_ce: true
    - name: "Include networks"
      ansible.builtin.include_role:
        name: "networks"
      vars:
        docker_networks:
          - haproxy
