---
ansible_action: converge
enable_pki_deploy_ca: false
pki_ca_file: "ca-{{ pki_ca_name }}.pem"
pki_ca_group: root
pki_ca_host: '{{ inventory_hostname_short }}'
pki_ca_name: 'ansible'
pki_ca_owner: root
