---
- name: Configure PROXY if enable_repositories_proxy is enable
  when:
    - enable_repositories_proxy | bool
    - ansible_action in ['converge', 'cleanup']
  block:
    - name: Facts
      ansible.builtin.include_tasks: "facts.yml"

    - name: Include tasks
      ansible.builtin.include_tasks: "{{ ansible_action }}_{{ ansible_facts.os_family | lower }}.yml"
