---
- name: Converge
  hosts: all
  tasks:
    - name: "Include openldap"
      ansible.builtin.include_role:
        name: "openldap"
      vars:
        enable_service_openldap: true
        openldap_dependencies: true
