---
galaxy_info:
  author: Yannick Sebastia
  description: Configure VIM
  license: GPL-3.0-only
  min_ansible_version: "2.1"
  namespace: ysebastia
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags: []
dependencies: []
